sonar.projectKey=yanke4_sopra-fs26-group-23-client
sonar.organization=yanke4

# relative paths to source directories. More details and properties are described
# at https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-scope/
sonar.sources=./app