export const REGION_INFO: Record<string, { name: string; bonus: number }> = {
  Iceland: { name: "British Isles", bonus: 5 },
  Ireland: { name: "British Isles", bonus: 5 },
  "Great Britain": { name: "British Isles", bonus: 5 },
  Norway: { name: "Scandinavia", bonus: 4 },
  Sweden: { name: "Scandinavia", bonus: 4 },
  Finland: { name: "Scandinavia", bonus: 4 },
  Estonia: { name: "Baltic States", bonus: 3 },
  Latvia: { name: "Baltic States", bonus: 3 },
  Lithuania: { name: "Baltic States", bonus: 3 },
  Belarus: { name: "Baltic States", bonus: 3 },
  Ukraine: { name: "Eastern Europe", bonus: 3 },
  Moldova: { name: "Eastern Europe", bonus: 3 },
  Romania: { name: "Eastern Europe", bonus: 3 },
  Balkan: { name: "Balkans", bonus: 5 },
  Greece: { name: "Balkans", bonus: 5 },
  Bulgaria: { name: "Balkans", bonus: 5 },
  Turkey: { name: "Balkans", bonus: 5 },
  Hungary: { name: "Central Europe", bonus: 5 },
  "Czech Republic": { name: "Central Europe", bonus: 5 },
  Slovakia: { name: "Central Europe", bonus: 5 },
  Poland: { name: "Central Europe", bonus: 5 },
  Portugal: { name: "Western Europe", bonus: 4 },
  Spain: { name: "Western Europe", bonus: 4 },
  France: { name: "Western Europe", bonus: 4 },
  Italy: { name: "Alpine", bonus: 3 },
  Switzerland: { name: "Alpine", bonus: 3 },
  Austria: { name: "Alpine", bonus: 3 },
  Belgium: { name: "Low Countries", bonus: 4 },
  Netherlands: { name: "Low Countries", bonus: 4 },
  Germany: { name: "Low Countries", bonus: 4 },
  Denmark: { name: "Low Countries", bonus: 4 },
};

export const REGION_COLORS: Record<string, string> = {
  // British Isles
  Iceland: "#a855f7",
  Ireland: "#a855f7",
  "Great Britain": "#a855f7",
  // Scandinavia
  Norway: "#06b6d4",
  Sweden: "#06b6d4",
  Finland: "#06b6d4",
  // Baltic States
  Estonia: "#f59e0b",
  Latvia: "#f59e0b",
  Lithuania: "#f59e0b",
  Belarus: "#f59e0b",
  // Eastern Europe
  Ukraine: "#f87171",
  Moldova: "#f87171",
  Romania: "#f87171",
  // Balkans
  Balkan: "#ec4899",
  Greece: "#ec4899",
  Bulgaria: "#ec4899",
  Turkey: "#ec4899",
  // Central Europe
  Hungary: "#84cc16",
  "Czech Republic": "#84cc16",
  Slovakia: "#84cc16",
  Poland: "#84cc16",
  // Western Europe
  Portugal: "#60a5fa",
  Spain: "#60a5fa",
  France: "#60a5fa",
  // Alpine
  Italy: "#fb923c",
  Switzerland: "#fb923c",
  Austria: "#fb923c",
  // Low Countries
  Belgium: "#34d399",
  Netherlands: "#34d399",
  Germany: "#34d399",
  Denmark: "#34d399",
};

export const COUNTRY_CENTERS: Record<string, [number, number]> = {
  Spain: [-3.7, 40.4],
  Ukraine: [31.2, 48.4],
  Portugal: [-8.2, 39.4],
  Netherlands: [5.3, 52.1],
  Germany: [10.4, 51.2],
  Austria: [14.6, 47.5],
  Belgium: [4.5, 50.5],
  Lithuania: [23.9, 55.2],
  Slovakia: [19.7, 48.7],
  Belarus: [27.9, 53.7],
  Latvia: [24.6, 56.9],
  Ireland: [-8.2, 53.4],
  Hungary: [19.5, 47.2],
  Moldova: [28.8, 47.0],
  "Czech Republic": [15.5, 49.8],
  Switzerland: [8.2, 46.8],
  Romania: [25.0, 45.9],
  Bulgaria: [25.5, 42.7],
  Finland: [26.0, 64.0],
  Iceland: [-19.0, 65.0],
  Poland: [19.1, 51.9],
  Balkan: [20.5, 43.5],
  Italy: [12.6, 42.5],
  France: [2.2, 46.2],
  Greece: [22.0, 39.0],
  Turkey: [35.2, 39.9],
  "Great Britain": [-3.4, 55.4],
  Denmark: [9.5, 56.3],
  Sweden: [15.6, 60.1],
  Estonia: [25.0, 58.6],
  Norway: [8.5, 60.5],
};
